/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CoffeeNET.local.view;

import CoffeeNET.arcade.model.IRepoArcade;
import CoffeeNET.arcade.view.JFArcade;
import CoffeeNET.cliente.model.IRepoCliente;
import CoffeeNET.cliente.view.JFMenuCliente;
import CoffeeNET.local.model.IRepoLocal;
import CoffeeNET.product.model.IRepoProduct;
import CoffeeNET.product.view.JFCarta;

/**
 *
 * @author Javier
 */
public class JFLocalMenu extends javax.swing.JFrame {
    private IRepoArcade repoArcade;
    private IRepoCliente repoCliente;
    private IRepoLocal repoLocal;
    private IRepoProduct repoCarta;
    private int clienteSelected;

    public void setClienteSelected(int clienteSelected) {
        this.clienteSelected = clienteSelected;
    }

    /**
     * Creates new form JFLocalMenu
     */
    public JFLocalMenu(IRepoCliente repoCliente, IRepoLocal repoLocal, IRepoArcade repoArcade, IRepoProduct repoCarta) {
        this.repoCliente = repoCliente;
        this.repoLocal = repoLocal;
        this.repoArcade = repoArcade;        
        this.repoCarta = repoCarta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoLocalMenu = new javax.swing.JLabel();
        BotonCafeteria = new javax.swing.JButton();
        botonArcades = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoLocalMenu.setText("Una vez elegido el local, ¿Qué tienes pensado?");

        BotonCafeteria.setText("Ir a cafetería");
        BotonCafeteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCafeteriaActionPerformed(evt);
            }
        });

        botonArcades.setText("Ir a las arcades");
        botonArcades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArcadesActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver al menú");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonVolver)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoLocalMenu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonArcades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(BotonCafeteria)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(textoLocalMenu)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCafeteria)
                    .addComponent(botonArcades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        JFMenuCliente jfMenu = new JFMenuCliente(repoCliente, repoLocal, repoArcade, repoCarta);
        jfMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonArcadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArcadesActionPerformed
        JFArcade jfArcade = new JFArcade(repoCliente, repoLocal, repoArcade, repoCarta);
        jfArcade.setClienteSelected(clienteSelected);
        jfArcade.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonArcadesActionPerformed

    private void BotonCafeteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCafeteriaActionPerformed
        JFCarta jfCarta = new JFCarta(repoCliente, repoLocal, repoArcade, repoCarta);
        jfCarta.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonCafeteriaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCafeteria;
    private javax.swing.JButton botonArcades;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel textoLocalMenu;
    // End of variables declaration//GEN-END:variables
}
