/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CoffeeNET.cliente.view;

import CoffeeNET.arcade.model.IRepoArcade;
import CoffeeNET.local.model.Local;
import CoffeeNET.cliente.model.IRepoCliente;
import CoffeeNET.local.model.IRepoLocal;
import CoffeeNET.local.view.JFLocalMenu;
import CoffeeNET.product.model.IRepoProduct;
import java.util.Vector;

/**
 *
 * @author Javier
 */
public class JFMenuCliente extends javax.swing.JFrame {
    private IRepoCliente repoCliente;
    private IRepoLocal repoLocal;
    private IRepoArcade repoArcade;
    private IRepoProduct repoCarta;
    private int localSelected;
    private int clienteSelected;

    public void setClienteSelected(int clienteSelected) {
        this.clienteSelected = clienteSelected;
    }

    public int getLocalSelected() {
        return localSelected;
    }

    /**
     * Creates new form JFMenuCliente
     */
    public JFMenuCliente(IRepoCliente repoCliente, IRepoLocal repoLocal, IRepoArcade repoArcade, IRepoProduct repoCarta) {
        this.repoCliente = repoCliente;
        this.repoLocal = repoLocal;
        this.repoArcade = repoArcade;
        this.repoCarta = repoCarta;
        initComponents();
        leer();
    }

    /**
     * Imprime la lista de cliente
     * @return String
     */
    public void leer() {
        Vector<Local> locales = (Vector<Local>) repoLocal.read();
        for(int i = 0; i<locales.size(); i++){
            comboListaLocales.addItem(locales.get(i).getDireccion());
        }            
        //jListCliente.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoBienvenida = new javax.swing.JLabel();
        comboListaLocales = new javax.swing.JComboBox<>();
        botonOk = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoBienvenida.setText("¿En qué local estás?");

        comboListaLocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboListaLocalesActionPerformed(evt);
            }
        });

        botonOk.setText("Seleccionar Local");
        botonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOkActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonOk)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoBienvenida)
                        .addGap(59, 270, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(comboListaLocales, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(textoBienvenida)
                .addGap(18, 18, 18)
                .addComponent(comboListaLocales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOk)
                    .addComponent(botonVolver))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboListaLocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboListaLocalesActionPerformed
                    
    }//GEN-LAST:event_comboListaLocalesActionPerformed

    private void botonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOkActionPerformed
        JFLocalMenu jfMeLocal = new JFLocalMenu(repoCliente, repoLocal, repoArcade, repoCarta);
        localSelected = comboListaLocales.getSelectedIndex();
        jfMeLocal.setClienteSelected(clienteSelected);
        jfMeLocal.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonOkActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        JFLoginCliente jfLogin = new JFLoginCliente(repoCliente, repoLocal, repoArcade, repoCarta);
        jfLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVolverActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOk;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> comboListaLocales;
    private javax.swing.JLabel textoBienvenida;
    // End of variables declaration//GEN-END:variables
}
